'Coverage: Heart API':
  stage: test
  extends:
    - .install
    - .only-master
  dependencies:
    - Build for master
  script:
    # As of latest version of Rush (5.18 at the moment),
    # there is no way to run a custom command for a single package only.
    # There is an open issue to provide such a feature: https://github.com/microsoft/rushstack/issues/1399.
    # Once this feature will be live, the following lines will be replaceable by:
    # - node common/scripts/install-run-rush.js test --coverage --verbose --project @fabernovel/heart-api
    - npm -g install pnpm@3.6.2
    - cd modules/heart-api
    - pnpm run test -- --coverage
  coverage: /Branches\s+:\s\d+.?\d+/
