image: node:10

cache:
  paths:
    - common/temp/node_modules/

Lint:
  stage: build
  only:
    - merge_requests
  script:
    - echo 'Installing...'
    - node common/scripts/install-run-rush.js install

    - echo 'Linting...'
    - node common/scripts/install-run-rush.js lint

Changes:
  stage: build
  only:
    # required to access the $CI_MERGE_REQUEST_TARGET_BRANCH_NAME environment variable
    - merge_requests
  script:
    - echo 'Checking for missing change logs...'
    # update the rush.json repository url with the one used by the CI, to make the 'rush change' command works
    - sed -i -e "s/git@gitlab.com:/https:\/\/gitlab-ci-token:${CI_JOB_TOKEN}@gitlab.com\//g" rush.json
    - git fetch origin $CI_MERGE_REQUEST_TARGET_BRANCH_NAME -a
    - node common/scripts/install-run-rush.js change --verify --target-branch origin/$CI_MERGE_REQUEST_TARGET_BRANCH_NAME

# Publish to NPM:
#   stage: deploy
#   only:
#     - tags
#   script:
#     - echo 'Installing...'
#     - node common/scripts/install-run-rush.js install

#     - echo 'Publishing ...'
#     - node common/scripts/install-run-rush.js publish --apply --set-access-level public --npm-auth-token ${NPM_TOKEN}
