image: node:10

cache:
  paths:
    - common/temp/node_modules/

Lint:
  stage: build
  script:
    - echo 'Installing...'
    - node common/scripts/install-run-rush.js install

    - echo 'Linting...'
    - node common/scripts/install-run-rush.js lint

Changes:
  stage: build
  script:
    - echo 'Checking for missing change logs...'
    # allows the rush change command to work, by updating the rush.json repository url with the one used by the CI
    - sed -i -e "s/git@gitlab.com:/https:\/\/gitlab-ci-token:${CI_JOB_TOKEN}@gitlab.com\//g" rush.json
    - git fetch origin master:refs/remotes/origin/master -a
    - node common/scripts/install-run-rush.js change --verify

# Publish to NPM:
#   stage: deploy
#   only:
#     - tags
#   script:
#     - echo 'Installing...'
#     - node common/scripts/install-run-rush.js install

#     - echo 'Publishing ...'
#     - node common/scripts/install-run-rush.js publish --apply --set-access-level public --npm-auth-token ${NPM_TOKEN}
