# Documentation for this file: https://prettier.io/docs/en/configuration.html
printWidth: 110
semi: false
plugins:
  - "./common/autoinstallers/rush-prettier/node_modules/prettier-plugin-packagejson"
