# This operation use artifacts created and stored during the "Build for master" job.
# This speeds up this job by avoiding to execute additional operations on the repository (like Rush commands).
🚀 Publish the website to production:
  stage: deploy
  extends:
    - .only-master
  dependencies:
    - Build for master
  before_script:
    # Grab Firebase CLI
    - npm install -g firebase-tools
  script:
    # https://firebase.google.com/docs/cli?authuser=0#cli-ci-systems
    # Authentication is made through the FIREBASE_TOKEN environment variable
    - cd website
    - firebase deploy

🔬 Analyze the website:
  stage: test
  variables:
    # Non-sensitive environment variables are put here.
    # See the repository configuration for sensitive ones
    OBSERVATORY_API_URL: https://http-observatory.security.mozilla.org/api/v1/
    OBSERVATORY_ANALYZE_URL: https://observatory.mozilla.org/analyze/
    SLACK_CHANNEL_ID: heart-test
  only:
    - schedules
  script:
    - cd website/ci
    - npm init --yes
    - npm install --save-dev
      @fabernovel/heart-cli
      @fabernovel/heart-dareboost
      @fabernovel/heart-lighthouse
      @fabernovel/heart-observatory
      @fabernovel/heart-ssllabs-server
      @fabernovel/heart-slack
    - npx heart dareboost --file dareboost.json
    - npx heart lighthouse --file lighthouse.json
    - npx heart observatory --file observatory.json
    - npx heart ssllabs-server --file ssllabs-server.json
