name: Check code

on:
  pull_request:
    types: [opened, synchronize, reopened]

jobs:
  check:
    name: 🧹 Lint & format
    runs-on: ubuntu-latest
    timeout-minutes: 5
    defaults:
      run:
        shell: bash

    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Setup Moon
        uses: moonrepo/setup-toolchain@v0
        with:
          auto-install: true

      - name: Lint & format
        run: moon ci :check
        env:
          # disable Chrome download on puppeteer install. see https://pptr.dev/api/puppeteer.configuration
          PUPPETEER_SKIP_CHROME_DOWNLOAD: true
