name: Pull request validation

on:
  pull_request:
    types: [opened, synchronize, reopened, edited]

jobs:
  changelog_lint:
    name: 📝 Missing changelog
    runs-on: ubuntu-latest
    container: node:14-alpine # Matches the version defined in .nmvrc and rush.json
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 2
      - name: 📝 Missing changelog
        run: node common/scripts/install-run-rush.js change --verify
  test:
    name: 💅 Lint & 🐛 Test
    runs-on: ubuntu-latest
    container: node:14 # Matches the version defined in .nmvrc and rush.json
    steps:
      - name: Install Google Chrome
        run: |
          wget -q -O - https://dl-ssl.google.com/linux/linux_signing_key.pub | apt-key add -
          sh -c 'echo "deb [arch=amd64] http://dl.google.com/linux/chrome/deb/ stable main" >> /etc/apt/sources.list.d/google.list'
          apt-get update
          apt-get install --yes google-chrome-stable
      - uses: actions/checkout@v3
        with:
          fetch-depth: 2
      - name: Rush install
        run: node common/scripts/install-run-rush.js install
      - name: Rush rebuild
        run: node common/scripts/install-run-rush.js rebuild --verbose
      - name: 💅 Lint
        run: node common/scripts/install-run-rush.js lint
      - name: 🐛 Test
        run: node common/scripts/install-run-rush.js test --verbose
