name: 🧹 Pull request

on:
  pull_request:
    types: [opened, synchronize, reopened]

jobs:
  syntax_changelog:
    name: Syntax & changelog
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 2

      - uses: actions/setup-node@v3
        with:
          node-version-file: .nvmrc

      - name: Install
        run: node common/scripts/install-run-rush.js install

      - name: 🏗 Build
        run: node common/scripts/install-run-rush.js rebuild

      - name: 📝 Verify missing changelogs
        run: node common/scripts/install-run-rush.js change --target-branch origin/$GITHUB_BASE_REF --verify -v

      - name: 💅 Lint
        run: node common/scripts/install-run-rush.js lint --verbose # --verbose allows to display warnings from ESLint

  test:
    name: Test
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node_version: [18, 19]

    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 2

      - uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node_version }}

      - name: Install
        run: node common/scripts/install-run-rush.js install

      - name: 🏗 Build
        run: node common/scripts/install-run-rush.js rebuild

      - name: 🐛 Test
        run: node common/scripts/install-run-rush.js test
