name: 🧹 Pull request

on:
  pull_request:
    types: [opened, synchronize, reopened, edited]

jobs:
  pull-request:
    name: Pull request
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 2

      - uses: actions/setup-node@v3
        with:
          # Matches the version defined in .nmvrc and rush.json
          node-version: 14

      - name: Install
        run: node common/scripts/install-run-rush.js install

      - name: 🏗 Build
        run: node common/scripts/install-run-rush.js rebuild

      - name: 📝 Verify missing changelogs
        run: node common/scripts/install-run-rush.js change --target-branch $GITHUB_BASE_REF --verify -v

      - name: 💅 Lint
        run: node common/scripts/install-run-rush.js lint

      - name: 🐛 Test
        run: node common/scripts/install-run-rush.js test
