name: 🚀 Publish packages

on:
  workflow_dispatch:
    inputs:
      MODE:
        description: Publication mode
        type: choice
        options:
          # Simulate the publication
          - simulate
          # Do the publication
          - publish
        default: simulate
        required: true
      VERSION_POLICY:
        description: Indicates how to increment packages version number
        type: choice
        options:
          # Increments according to their own minor or patch increment (depends of the type of changes made to each package)
          - individualVersion
          # Increments to the same major version. Use only for major releases.
          - lockStepVersion
        default: "individualVersion"
        required: true
  # debug
  pull_request:
    types: [opened, synchronize, reopened]

jobs:
  publish:
    runs-on: ubuntu-latest
    env:
      MODE: ${{ inputs.MODE }}
      SOURCE_BRANCH: master # Force the master branch to be deployed: avoid the publication of WIP code from other branches
      TARGET_BRANCH: release/${{ github.run_id }}
      VERSION_POLICY: ${{ inputs.VERSION_POLICY }}
    permissions:
      contents: write
      pull-requests: write

    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 2
          ref: ${{ env.SOURCE_BRANCH }}

      - uses: actions/setup-node@v3
        with:
          node-version-file: .nvmrc

      - name: Git config user
        uses: snow-actions/git-config-user@v1.0.0
        with:
          name: Heart
          email: heart@fabernovel.com

      - name: Debug
        run: env

      - name: Create origin/${{ env.TARGET_BRANCH }} branch and switch to it
        run: git checkout -b $TARGET_BRANCH

      # As we are using Rush version policies feature, we need to bump versions first:
      # https://rushjs.io/pages/maintainer/publishing/#publishing-process-when-version-policies-are-used
      - name: Bump packages versions numbers
        if: ${{ env.MODE == 'publish' }}
        run: node common/scripts/install-run-rush.js version --bump --target-branch $TARGET_BRANCH --version-policy $VERSION_POLICY

      - name: Simulate a publication to npmjs.org with the ${{ env.VERSION_POLICY }} version policy
        if: ${{ env.MODE == 'simulate' }}
        run: node common/scripts/install-run-rush.js publish --include-all --target-branch $TARGET_BRANCH --version-policy $VERSION_POLICY

      # - name: Publish to npmjs.org with the ${{ env.VERSION_POLICY }} version policy
      #   if: ${{ env.MODE == 'publish' }}
      #   run: node common/scripts/install-run-rush.js publish --include-all --target-branch $TARGET_BRANCH --version-policy $VERSION_POLICY --publish

      - name: Create Pull Request
        run: gh pr create --base $SOURCE_BRANCH --head $TARGET_BRANCH --reviewer bgatellier
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
