on:
  # Reusable workflow: https://docs.github.com/en/actions/sharing-automations/reusing-workflows
  workflow_call:
    inputs:
      package-id:
        required: true
        type: string

jobs:
  sonarcloud:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Download code coverage reports
        uses: actions/download-artifact@v4
        with:
          name: code-coverage-report

      - uses: SonarSource/sonarcloud-github-action@v3
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}  # Needed to get PR information, if any
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
        with:
          projectBaseDir: packages/${{ inputs.package-id }}/
          args: >
            -Dsonar.organization=bgatellier
            -Dsonar.projectKey=scodi-${{ inputs.package-id }}
            -Dsonar.sources=src/
            -Dsonar.tests=tests/
            -Dsonar.javascript.lcov.reportPaths=coverage/lcov.info
