name: Tests

on:
  pull_request:
    types: [opened, synchronize, reopened]

jobs:
  test:
    name: 🐛 Run tests
    runs-on: ubuntu-latest
    timeout-minutes: 5
    defaults:
      run:
        shell: bash
    strategy:
      matrix:
        node_version: [18, 19, 20, 21]

    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Set Node.js version
        run: sed -Ei 's/(node = ).*/\1"^${{ matrix.node_version}}"/' .prototools

      - name: Setup Moon
        uses: moonrepo/setup-toolchain@v0
        with:
          auto-install: true

      - name: Run tests
        if: ${{ matrix.node_version != '18' }}
        run: moon ci :test

      - name: Run tests and generate coverage reports
        if: ${{ matrix.node_version == '18' }}
        run: moon ci :coverage

      - name: Archive code coverage reports
        if: ${{ matrix.node_version == '18' }}
        uses: actions/upload-artifact@v4
        with:
          name: code-coverage-reports
          path: modules/**/clover.xml
          retention-days: 1

  coverage:
    needs: test
    name: ⬆️ Upload code coverage reports to Codecov
    runs-on: ubuntu-latest
    timeout-minutes: 5
    defaults:
      run:
        shell: bash

    steps:
      - name: Download reports from previous job
        uses: actions/download-artifact@v4
        with:
          name: code-coverage-reports

      - name: Upload reports to Codecov
        uses: codecov/codecov-action@v4
        with:
          fail_ci_if_error: true
          token: ${{ secrets.CODECOV_TOKEN }}
