# https://docs.github.com/en/actions/using-workflows/reusing-workflows
on:
  workflow_call:
    inputs:
      module_name:
        required: true
        type: string

jobs:
  upload_coverage_report:
    name: Upload the coverage report to Codecov
    runs-on: ubuntu-latest
    defaults:
      run:
        shell: bash

    steps:
      - uses: actions/checkout@v3

      - name: Download code coverage reports
        uses: actions/download-artifact@v3
        with:
          name: code-coverage-reports
          path: modules/

      - name: ⤒ Upload coverage report for ${{ inputs.module_name }} module
        uses: codecov/codecov-action@v3
        with:
          fail_ci_if_error: true
          files: ./modules/${{ inputs.module_name }}/coverage/clover.xml
          flags: ${{ inputs.module_name }}
